"""
Week 4 Day 4: correlating a build error's symbol to the changelog
section that explains it.

find_relevant_changelog_section tries backtick-quoted matches first,
then falls back to a plain substring search over each section's prose.
That fallback exists because of a real finding, not a hypothetical:
this project's own real uuid v3->v9 changelog (fetched live in
Week 3/4 testing) is auto-generated by standard-version tooling and
has ZERO backtick code spans -- its actual breaking-change text is
plain prose ("...used to be the v4() method..."). A backtick-only
index finds nothing on exactly the real regression this project hit.
tests/test_agent_revise.py's approach (small, clearly-labeled synthetic
fixtures) is followed here for the same reason: this module doesn't
need network access to prove its own text-matching logic is correct.
"""
from __future__ import annotations

from agent.changelog import find_relevant_changelog_section

_BACKTICK_CHANGELOG = """## v2.0.0

### Breaking Changes

- `HttpClient.request` now requires an explicit timeout argument.
- `OldHelper` has been removed entirely, use `NewHelper` instead.

## v1.5.0

### Features

- Added `retry` option to `HttpClient.request`.
"""

_PROSE_CHANGELOG = """## [7.0.0](https://github.com/uuidjs/uuid/compare/v3.4.0...v7.0.0) (2020-02-24)

### BREAKING CHANGES

- The default export, which used to be the v4() method, has been removed.
- Deep imports of the different uuid version functions are deprecated.

## [6.0.0](https://github.com/x/x/compare/v5...v6) (2019-01-01)

### Features

- Added a new logging option, nothing to do with this test's real subject.
"""


def test_backtick_exact_match_found():
    section = find_relevant_changelog_section(_BACKTICK_CHANGELOG, "OldHelper")
    assert section is not None
    assert "OldHelper" in section
    assert "removed entirely" in section


def test_backtick_qualified_symbol_matches_short_name():
    # Build error reports the bare method name; changelog documents it
    # dotted/qualified -- must still match via the shared short name.
    section = find_relevant_changelog_section(_BACKTICK_CHANGELOG, "request")
    assert section is not None
    assert "HttpClient.request" in section


def test_prose_fallback_finds_real_style_uuid_mention():
    section = find_relevant_changelog_section(_PROSE_CHANGELOG, "v4")
    assert section is not None
    assert "v4() method" in section
    assert "logging option" not in section  # only the matching section, not all of them


def test_prose_fallback_is_word_bounded_not_substring():
    # "v4" must not spuriously match inside an unrelated longer token
    # like "v40" or "xv4y" -- \b enforces this.
    changelog = "## v1.0.0\n\nSomething about xv4y and v40 but not the real symbol.\n"
    assert find_relevant_changelog_section(changelog, "v4") is None


def test_no_match_returns_none_not_empty_string():
    assert find_relevant_changelog_section(_BACKTICK_CHANGELOG, "TotallyUnrelatedSymbol") is None


def test_empty_symbol_or_changelog_returns_none():
    assert find_relevant_changelog_section(_BACKTICK_CHANGELOG, "") is None
    assert find_relevant_changelog_section("", "request") is None
